version: '3.9'
services:
  nest:
    build: . 
    
    links:
      - postgres
    ports:
      - '3000:3000' 

    env_file:
      - .env

  postgres:
    image: 'postgres:latest'
    restart: always
    volumes:
      - 'nest-postgres:/var/lib/postgresql/data'
    environment:
      - POSTGRES_DB=guitars
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    ports:
      - '5432:5432'

  adminer: 
    image: 'adminer:latest'
    ports: 
     - '8080:8080'

volumes:
  nest-postgres:

